CREATE TABLE highscore (
    user_id                  UUID   NOT NULL,
    mission_id               UUID   NOT NULL,
    player_0_max_velocity    BIGINT NOT NULL DEFAULT 0,
    player_0_total_distance  BIGINT NOT NULL DEFAULT 0,
    player_1_max_velocity    BIGINT NOT NULL DEFAULT 0,
    player_1_total_distance  BIGINT NOT NULL DEFAULT 0,
    player_2_max_velocity    BIGINT NOT NULL DEFAULT 0,
    player_2_total_distance  BIGINT NOT NULL DEFAULT 0,
    player_3_max_velocity    BIGINT NOT NULL DEFAULT 0,
    player_3_total_distance  BIGINT NOT NULL DEFAULT 0,
    player_4_max_velocity    BIGINT NOT NULL DEFAULT 0,
    player_4_total_distance  BIGINT NOT NULL DEFAULT 0,
    player_5_max_velocity    BIGINT NOT NULL DEFAULT 0,
    player_5_total_distance  BIGINT NOT NULL DEFAULT 0,
    player_6_max_velocity    BIGINT NOT NULL DEFAULT 0,
    player_6_total_distance  BIGINT NOT NULL DEFAULT 0,
    player_7_max_velocity    BIGINT NOT NULL DEFAULT 0,
    player_7_total_distance  BIGINT NOT NULL DEFAULT 0,
    player_8_max_velocity    BIGINT NOT NULL DEFAULT 0,
    player_8_total_distance  BIGINT NOT NULL DEFAULT 0,
    player_9_max_velocity    BIGINT NOT NULL DEFAULT 0,
    player_9_total_distance  BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, mission_id)
);
