[package]
name = "hexagon_egui"
version = "0.1.0"
edition = "2024"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[dependencies]
egui = "0.34.2"
eframe = { version = "0.34.2", features = ["persistence"] }
hexagon_engine = { path = "../hexagon_engine" }

indexmap.workspace = true
strum.workspace = true
log = "0.4.27"
serde.workspace = true
serde_json.workspace = true

# native:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.11.8"
rodio = { version = "0.22", features = ["mp3"] }

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.121"
wasm-bindgen-futures = "0.4.71"
web-sys = "0.3.70"              # to access the DOM (to hide the loading text)
