[package]
name = "hexagon_egui"
version = "0.1.0"
edition = "2024"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]


[dependencies]
egui = "0.34.2"
egui_extras = "0.34.2"
eframe = { version = "0.34.2", features = ["persistence"] }
egui-async = "0.4"
hexagon_engine = { path = "../hexagon_engine" }
hexagon_frontend_reqwest = { path = "../hexagon_frontend_reqwest" }
hexagon_types = { path = "../hexagon_types" }


uuid.workspace = true
indexmap.workspace = true
strum.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true

# native (desktop + android):
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber.workspace = true
tokio.workspace = true

# desktop only (not android, not wasm):
[target.'cfg(all(not(target_arch = "wasm32"), not(target_os = "android")))'.dependencies]
rodio = { version = "0.22", features = ["mp3"] }


# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.121"
wasm-bindgen-futures = "0.4.71"
web-sys = "0.3.70"              # to access the DOM (to hide the loading text)
log = "0.4"
