[package]
name = "hexagon_db"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "postgres",
    "uuid",
    "json",
    "migrate",
] }
uuid = { version = "1", features = ["v4", "serde"] }
serde.workspace = true
serde_json.workspace = true
secrecy.workspace = true
